version: '3'
services:
  engine-ia-java8:
    image: opentosca/engine-ia:latest-jdk8
    ports:
      - '8098:8080'
  engine-ia-java17:
    image: opentosca/engine-ia:latest-jdk17
    ports:
      - '8099:8080'
  engine-plan:
    image: opentosca/ode:latest
    environment:
      _JAVA_OPTIONS: "-Xmx3048m -Xms512m -Xss4m"
    ports:
      - '9763:9763'
  engine-plan-bpmn:
    image: opentosca/camunda-bpmn:latest
    ports:
      - '8092:8080'
  container:
    image: opentosca/container:latest
    ports:
      - '1337:1337'
      - '1883:1883' # MQTT
      - '8081-8083:8081-8083'
      - '8085-8087:8085-8087'
    environment:
      CONTAINER_HOSTNAME: 172.17.0.1
      ENGINE_IA_HOSTNAME: 172.17.0.1
      ENGINE_IA_PORT: 8098
      ENGINE_IA_JAVA17_HOSTNAME: 172.17.0.1
      ENGINE_IA_JAVA17_PORT: 8099
      ENGINE_PLAN_BPEL_HOSTNAME: 172.17.0.1
      ENGINE_PLAN_BPMN_HOSTNAME: 172.17.0.1
      ENGINE_PLAN_BPMN_PORT: 8092
      CONTAINER_DEPLOYMENT_TESTS: 'false'