version: '3'
services:
  container:
    image: opentosca/container:latest
    ports:
      - '1337:1337'
      - '1883:1883' # MQTT
      - '8081-8087:8081-8087'
    environment:
      CONTAINER_HOSTNAME: container
      ENGINE_IA_HOSTNAME: engine-ia
      ENGINE_IA_PORT: 8080
      CONTAINER_REPOSITORY_HOSTNAME: container-repository
      CONTAINER_REPOSITORY_PORT: 8080
      ENGINE_PLAN_BPEL_HOSTNAME: engine-plan
      ENGINE_PLAN_BPMN_HOSTNAME: engine-plan-bpmn
      ENGINE_PLAN_BPMN_PORT: 8080
      CONTAINER_DEPLOYMENT_TESTS: 'false'
    networks:
      - opentosca
  engine-ia-java8:
    image: opentosca/engine-ia:latest-jdk8
    ports:
      - '8098:8080'
    networks:
      - opentosca
  engine-ia-java17:
    image: opentosca/engine-ia:latest-jdk17
    ports:
      - '8099:8080'
    networks:
      - opentosca
  engine-plan:
    image: opentosca/ode:latest
    environment:
      _JAVA_OPTIONS: "-Xmx3048m -Xms512m -Xss4m"
    ports:
      - '9763:9763'
    networks:
      - opentosca
  engine-plan-bpmn:
    image: opentosca/camunda-bpmn:latest
    ports:
      - '8092:8080'
    networks:
      - opentosca
  container-repository:
    image: opentosca/winery:latest
    environment:
      WINERY_PORT: 8091
      WORKFLOWMODELER_PORT: 8091
      TOPOLOGYMODELER_PORT: 8091
      WINERY_REPOSITORY_URL: https://github.com/OpenTOSCA/tosca-definitions-management-features
    ports:
      - '8091:8080'
    networks:
      - opentosca